# Change these first
owner: ccbikai # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MT.CI
    url: https://mt.ci
  - name: MT.CD
    url: https://mt.cd
  - name: Kai.Bi
    url: https://kai.bi
  - name: miantiao.me
    url: https://miantiao.me
  - name: chi.miantiao.me
    url: https://chi.miantiao.me
  - name: feed.miantiao.me
    url: https://feed.miantiao.me
  - name: HTML.ZONE
    url: https://html.zone
  - name: LU
    url: lu.kai.bi
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.miantiao.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Uptime Title"
  introMessage: "Uptime Message"
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://mt.ci

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
